In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('vaccinations.csv')
df.head()

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0

In [3]:
df.drop_duplicates(subset='location', keep='last', inplace=True)

In [4]:
df.head()

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
93,Afghanistan,AFG,2021-05-26,590454.0,479372.0,111082.0,NaN,6768.0,1.52,1.23,0.29,174.0
233,Africa,OWID_AFR,2021-05-28,30840057.0,23694262.0,7521225.0,960186.0,519243.0,2.30,1.77,0.56,387.0
371,Albania,ALB,2021-05-27,759043.0,481788.0,277255.0,10057.0,7900.0,26.38,16.74,9.63,2745.0
393,Algeria,DZA,2021-02-19,75000.0,NaN,NaN,NaN,3748.0,0.17,NaN,NaN,85.0
506,Andorra,AND,2021-05-17,32317.0,27613.0,4704.0,NaN,98.0,41.83,35.74,6.09,1268.0

In [5]:
df.loc[(df['location']=="Greece")]

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
8071,Greece,GRC,2021-05-28,5402105.0,3532531.0,1967849.0,96750.0,83875.0,51.83,33.89,18.88,8047.0

In [6]:
df['location'] == "Africa"

93       False
233       True
371      False
393      False
506      False
         ...
22439    False
22617    False
22618    False
22663    False
22763    False
Name: location, Length: 225, dtype: bool

In [8]:
df.loc[(df['location']=="Europe")]

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
6513,Europe,OWID_EUR,2021-05-28,348088946.0,231710429.0,119219879.0,3484190.0,4315057.0,46.49,30.95,15.92,5764.0

In [10]:
df['total_vaccinations'].max()

1844019777.0

In [18]:
df.loc(df[df['total_vaccinations']['location']])

KeyError: 'location'